# -*- coding: utf-8 -*-
"""GB657- Final Natural Language Processing with Disaster Tweets

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17EMRao5dkgwOnL2w00goyUnqNBE9tvBX

##Natural Language Processing with Disaster Tweets
Emergency response teams monitor social media platforms such as Twitter to detect disasters in real time. A machine learning model that automatically identifies tweets referring to real disasters can help analysts filter large volumes of social media data and focus on posts that may indicate genuine emergencies.

# Load Libraries and Dataset
"""

import pandas as pd
import numpy as np
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
!pip install wordcloud
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import seaborn as sns

import re
import nltk
from nltk.corpus import stopwords

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report

!pip install tensorflow
from tensorflow import keras #for nureal networks
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

!kaggle competitions download -c nlp-getting-started
!unzip nlp-getting-started.zip -d data

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

train.head()

"""# Data Exploration"""

# dataset shape
print("Train shape:", train.shape)
print("Test shape:", test.shape)

# column names
print("\nColumns:")
print(train.columns)

# check missing values
print("\nMissing values:")
print(train.isnull().sum())

"""The dataset is mostly clean. The text field has no missing values and will be the primary feature for modeling. location column contains many missing values and may be excluded from the analysis."""

train['target'].value_counts()

sns.countplot(x='target', data=train)
plt.title("Distribution of Disaster vs Non-Disaster Tweets")
plt.show()

"""The dataset is relatively balanced with slightly more non-disaster tweets (0) than disaster tweets (1)

#Prepare and Clean data
"""

train['processed_text'] = train['text']
train[['text','processed_text']].head()

"""Process the text into a more usable format(numbers) by:"""

#Remove Puntuation
def remove_punctuation(text):
    translator = str.maketrans('', '', string.punctuation)
    return text.translate(translator)

train['processed_text'] = train['processed_text'].apply(remove_punctuation)
train[['processed_text']].head()

#Convert Text to Lowercase
train['processed_text'] = train['processed_text'].str.lower()
train[['processed_text']].head()

#Remove Stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

train['processed_text'] = train['processed_text'].apply(
    lambda x: ' '.join([word for word in x.split() if word not in stop_words]))

train[['processed_text']].head()

#Lemmatization
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()
train['processed_text'] = train['processed_text'].apply(
    lambda x: ' '.join([lemmatizer.lemmatize(word) for word in x.split()]))
train[['processed_text']].head()

#Encode text.
tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(train['processed_text'])
y = train['target']

print("TF-IDF matrix shape:", X.shape)

X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

"""# Visualize data"""

disaster_text = ' '.join(train[train['target'] == 1]['processed_text'])
non_disaster_text = ' '.join(train[train['target'] == 0]['processed_text'])

#Disated Wordcloud
wordcloud_disaster = WordCloud(width=800, height=400, background_color='white').generate(disaster_text)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud_disaster, interpolation='bilinear')
plt.axis('off')
plt.title("Word Cloud for Disaster Tweets")
plt.show()

#Non-Disaster word cloud
wordcloud_non_disaster = WordCloud(width=800, height=400, background_color='white').generate(non_disaster_text)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud_non_disaster, interpolation='bilinear')
plt.axis('off')
plt.title("Word Cloud for Non-Disaster Tweets")
plt.show()

"""# Logistic Regression"""

log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train, y_train)

#Make predictions
y_pred = log_model.predict(X_val)

accuracy = accuracy_score(y_val, y_pred)
f1 = f1_score(y_val, y_pred)

print("Accuracy:", accuracy)
print("F1 Score:", f1)

cm = confusion_matrix(y_val, y_pred)

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Logistic Regression Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""Logistic regression provides a strong baseline, correctly classifying most tweets,though some disaster tweets are missed.

# Neural Network
"""

#Define the neural network model
model = Sequential([Dense(128, activation='relu', input_shape=(X_train.shape[1],)),Dense(64, activation='relu'),Dense(1, activation='sigmoid')])

#Compile the model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

model.summary()

#Train model
history = model.fit(
    X_train.toarray(),
    y_train,
    validation_data=(X_val.toarray(), y_val),
    epochs=5,
    batch_size=32,
    verbose=1
)

y_pred_nn = (model.predict(X_val.toarray()) > 0.5).astype("int32")
y_pred_nn = y_pred_nn.flatten()

accuracy_nn = accuracy_score(y_val, y_pred_nn)
f1_nn = f1_score(y_val, y_pred_nn)

print("Accuracy:", accuracy_nn)
print("F1 Score:", f1_nn)

#Plot confusion matrix
cm_nn = confusion_matrix(y_val, y_pred_nn)

sns.heatmap(cm_nn, annot=True, fmt='d', cmap='Blues')
plt.title("Neural Network Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""The neural network achieved an accuracy of 0.779 and an F1 score of 0.734 on the validation set.While it correctly identified many tweets, it produced more false positives and false negatives than the logistic regression model, indicating that the simpler baseline performed slightly better with TF-IDF features for this task.

# Kaggle Submission
"""

# Prepare test data, transform it, generate predictions, create submission file, and download it

test['processed_text'] = test['text']

test['processed_text'] = test['processed_text'].apply(remove_punctuation)
test['processed_text'] = test['processed_text'].str.lower()
test['processed_text'] = test['processed_text'].apply(
    lambda x: ' '.join([word for word in x.split() if word not in stop_words])
)
test['processed_text'] = test['processed_text'].apply(
    lambda x: ' '.join([lemmatizer.lemmatize(word) for word in x.split()])
)

X_test = tfidf.transform(test['processed_text'])

test_predictions = log_model.predict(X_test)

submission = pd.DataFrame({
    'id': test['id'],
    'target': test_predictions
})

submission.to_csv('submission.csv', index=False)

print("Submission file created successfully.")
print(submission.head())

from google.colab import files
files.download('submission.csv')